# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SessionsController, type: :controller do
  let(:user) { create(:user) }

  describe '#github' do
    before do
      request.env['devise.mapping'] = Devise.mappings[:user]
      request.env['omniauth.auth'] = OmniAuth.config.mock_auth[:github]
      allow(User).to receive(:find_or_create_by).and_return(user)
    end

    it 'Signs in the user' do
      get :github
      expect(controller.user_signed_in?).to eq(true)
    end
  end
  describe '#logout' do
    before do
      request.env['devise.mapping'] = Devise.mappings[:user]
      sign_in(user)
    end
    it 'Signs out the user' do
      get :logout
      expect(controller.user_signed_in?).to eq(false)
    end
    it 'Redirects to root path' do
      get :logout
      assert_response :redirect
    end
  end
end
